# Generated by Django 3.2 on 2021-04-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_learning_prerequisite_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='learning',
            name='discription',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='discription',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='discription',
            field=models.CharField(default='', max_length=20),
        ),
    ]
